# https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
version: '3'
services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      NEO4j_dbms.security.auth_enabled: 'true'
      NEO4j_AUTH: 'neo4j/${NEO4J_PASSWORD}'
      # Raise memory limits
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms.memory.heap.initial_size: 2G
      NEO4J_dbms_memory_heap_max__size: 2G
