# https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
version: '3.8'
networks:
  neo4j_network:
    driver: bridge

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    # pass .env file to container
    env_file: .env
    ports:
      - 7474:7474 # web client
      - 7687:7687 # db default port
    volumes:
      - ./neo4j:/data
    environment:
      - NEO4j_dbms.security.auth_enabled='true'
      # install graph-data-science plugin
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=True
      # listen to incoming connections
      - NEO4J_dbms.connector.bolt.listen_address=0.0.0.0:7687
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
    networks:
      - neo4j_network

  app:
    build: .
    container_name: app
    env_file: .env
    command: >
      sh -c "sleep 15"
    links:
      - neo4j
    depends_on:
      - neo4j
    networks:
      - neo4j_network
