# https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    # pass .env file to container
    env_file: .env
    ports:
      - 7474:7474 # web client
      - 7687:7687 # db default port
    volumes:
      - ./neo4j:/data
      - ./import:/import
    environment:
      - NEO4j_dbms.security.auth_enabled='true'
      # listen to incoming connections
      - NEO4J_dbms.connector.bolt.listen_address=0.0.0.0:7687
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G

  dataloader:
    image: python:3.8-buster
    container_name: dataloader
    env_file: .env
    ports:
      - 5002:5002
    volumes:
      - ./neo4j:/data
      - ./import:/import
      - ./poetry.lock:/poetry.lock
      - ./pyproject.toml:/pyproject.toml
      - ./loader.py:/loader.py
    command: >
      sh -c "mv data/*csv import/ &&
             pip install poetry &&
             poetry install &&
             poetry run python -m loader.py --file 'data/query_constraints.cypher'"
    links:
      - neo4j
    depends_on:
      - neo4j

volumes:
  neo4j:
