# https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    # pass .env file to container
    env_file: .env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      # cannot move files to import/ folder in neo4j because it's read-only
      # https://neo4j.com/docs/operations-manual/current/configuration/file-locations/
      # but can move from docker neo4j bash terminal
      - ./neo4j:/data
    environment:
      - NEO4j_dbms.security.auth_enabled='true'
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
  import:
    build: .
    command: >
      sh -c "data/loader.sh"
    depends_on:
      - neo4j
