version: '3.8'
networks:
  neo4j_network:
    driver: bridge

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    # pass .env file to container
    env_file: .env
    ports:
      - 7474:7474 # web client
      - 7687:7687 # db default port
    volumes:
      - ./neo4j:/var/lib/neo4j/import
    environment:
      - NEO4j_dbms.security.auth_enabled='true'
      # install graph-data-science plugin
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=True
      # listen to incoming connections
      - NEO4J_dbms.connector.bolt.listen_address=0.0.0.0:7687
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
    networks:
      - neo4j_network

  app:
    build: . # build from Dockerfile
    container_name: app
    env_file: .env
    environment:
      - WAIT_HOSTS=neo4j:7687
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    links:
      - neo4j
    command: >
      sh -c "/wait \
             && python -m loader --file 'neo4j/query_constraints.cypher' \
             && python -m loader --file 'neo4j/query_nodes.cypher' \
             && python -m loader --file 'neo4j/query_relationships.cypher'"
    networks:
      - neo4j_network
